print(3+4)
print(3-4)
print(3*4)
print(4%3)
print(3/4)
print(3**4)
print(4//3)

print('tama')
print('i dont have family name')
print('indonesia')
print('i dont know what to do so i am coding')

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type('tama'))
print(type('i dont have family name'))
print(type('indonesia'))
